added sauna pictogram
FreemapSlovakia/freemap-mapnik pull request #164
Opened 2020-11-18 10:39 UTC by seg-on

added sauna pictogram copied from OSM end edited to be black and white

2020-11-18 15:14 UTC, zdila requested changes
prosim sprav to voci vetve `develop`, nie `master`.

2020-11-18 15:14 UTC, zdila commented on additional.sql
> +('sauna');
saune by som urcite dal vyssiu prioritu ako napr renderovaniu brany (`gate`).

2020-11-18 15:14 UTC, zdila commented on mapping.yaml
> +			- sauna
toto je zle odsadene co robi tento yaml nevalidnym

2020-11-18 15:14 UTC, zdila commented on images/Sauna.svg
> +<?xml version="1.0" encoding="UTF-8" standalone="no"?>
nazov suboru ikon daj prosim malymi pismenami ako je to maju vsetky doterajsie ikony. inac to na*nix systemoch ani nepojde.

naviac ikona musi byt opravena aby mala biely, 50% outline, 1.5px - ako to maju vsetky ostatne ikony.

2020-11-18 15:14 UTC, zdila commented on legend.js
> +	poi('sauna', 'sauna', 'sauna'),
nezarovnane odsadenie

2020-11-19 20:07 UTC, closed without merging

2020-11-19 20:08 UTC, seg-on commented
pokúsil som sa zapracovať všetky pripomienky a dal som to do develop vetvy