Add paragliding icon
FreemapSlovakia/freemap-mapnik pull request #190
Opened 2021-06-17 07:41 UTC by seg-on

Added paragliding icon for sport=free_flying

2021-06-17 07:53 UTC, zdila requested changes

2021-06-17 07:53 UTC, zdila commented on images/free_flying.svg
> + <g transform="translate(-187.1 -49.85)">
please get rid of transformations (eg. use ungroup function in inkscape and then minify SVG again)

I am also missing a white glow as we use for other icons.

2021-06-17 07:53 UTC, zdila commented on legend.js
> +	poi('free_flying', 'paragliding', 'paraglajding'),
pls use spaces, not tabs

2021-06-17 09:45 UTC, seg-on commented
see if it's okay

2021-07-19 17:00 UTC, merged

2021-07-19 17:47 UTC, zdila commented on style/index.js
> +      .area(colors.grassy, 'wetland')
toto mazem lebo to renderuje wetland vsade. prosim pred pull-requestom otestuj ci to funguje

2021-07-19 17:54 UTC, zdila commented
vdaka, len nabuduce prosim dokoncit a lokalne otestovat. support som donokncil v https://github.com/FreemapSlovakia/freemap-mapnik/commit/da594304a12dc0089108a5d50c6179b914226867

2021-07-20 09:04 UTC, seg-on commented
bohužiaľ nemám teraz na čom by som to rozbehal a testoval